name: CI
run-name: ${{ github.actor }} está executando testes CI/CD
on: [push]
jobs:
  Execute-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: chmod 777 ./gradlew
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest
      - name: Upload Checkstyle reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-reports
          path: build/reports/checkstyle/
      - name: Run tests
        run: ./gradlew test
